version: '3.4'

services:
   seq:
    image: datalust/seq:latest

   sqldata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin@123
    image: mcr.microsoft.com/mssql/server:2019-latest

   basketdata:
    image: redis:alpine

   rabbitmq:
    image: rabbitmq:3-management-alpine

   identity.api:
    image: ${REGISTRY:-eshop}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
      - sqldata

   identitystore:
    image: ${REGISTRY:-eshop}/identitystore:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Identity/IdentityStore/Dockerfile
    depends_on:
      - sqldata

   basket.api:
    image: ${REGISTRY:-eshop}/basket.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
      - basketdata
      - identity.api
      - rabbitmq